- name: Make mariadb server file configuration
  template:
    src: server.cnf.j2
    dest: /etc/my.cnf.d/server.cnf
  notify: restart mariadb server
  when: ( ansible_distribution_file_variety == "RedHat" )

- name: Make mariadb server file configuration
  template:
    src: server.cnf.j2
    dest: /etc/mysql/mariadb.cnf
  notify: restart mariadb server
  when: ( ansible_distribution_file_variety == "Debian" )

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swappiness }}"
    state: present
  when:
    - configure_swappiness|bool

- name: Create log directory
  file:
    state: directory
    path: /var/log/mariadb
    owner: mysql
    group: mysql
    mode: 0755
  notify: set mariadb log selinux
  when: ( ansible_distribution_file_variety == "RedHat" )

- name: Create log directory
  file:
    state: directory
    path: /var/log/mariadb
    owner: mysql
    group: mysql
    mode: 0765
  when: ( ansible_distribution_file_variety == "Debian" )

- name: Configure MariaDB Logrotate
  template:
    src: mariadb_logrotate.j2
    dest: /etc/logrotate.d/mysql
  notify: restart mariadb server

- name: (DATABASE) Allow remote hosts to connect (Debian)
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    backrefs: yes
    regexp: '^bind-address'
    line: 'bind-address            = {{ bind-address }}'
    state: present
  notify: restart mariadb
  when: ansible_os_family == "Debian"

- name: (DATABASE) Allow remote hosts to connect (Red Hat)
  lineinfile:
    path: /etc/my.cnf.d/server.cnf
    state: present
    insertafter: '^\[mysqld\]'
    line: 'bind-address            = {{ bind-address }}'
  notify: restart mariadbrh
  when: ansible_os_family == "RedHat"